#!/usr/bin/env bash
# kb.sh — read the records back. The loop WRITES knowledge (intent, spec, plan,
# evidence, delivery, CLOSED, lessons, harvest); this is how a later feature —
# or a human — FINDS it and reads it without opening six files.
#
#   kb.sh index   [--store <dir>]                   regenerate the contents page
#   kb.sh list    [--store <dir> | --area <folder>]
#   kb.sh show    <slug | product area> [--store <dir> | --area <folder>]
#                                                   one feature as a digest, or one area page
#   kb.sh search  [--store <dir> | --area <folder>] [--limit N] <literal text>
#   kb.sh harvest [--store <dir> | --area <folder>] [--stale <days>]
#                                                   open features whose harvest.md is not in memory/ yet
#
# Store resolution: --store <dir> is a store (or a project's .sdlc); with
# neither flag the store is ./.sdlc. --area <folder> reads EVERY recognized
# store in that folder — a directory holding a PROJECT record written by
# init.sh --area — and nothing else: no arbitrary filesystem content, no
# symlinks followed, one level deep. The original checkout need not exist, so
# knowledge survives a deleted worktree.
#
# What is read: *.md and CLOSED under work/, archive/ and memory/.
# Never read: scratch/ (bulk evidence), approvals/ (machine records),
# progress.md (heartbeat), baseline.txt, checkpoint.md, verify-receipt.md,
# verify-baseline.md.
#
# `show` is a digest — goal, summary.md (templates/summary.md), delivery,
# unmerged harvest.md candidates, lesson titles, then the paths. A name that is
# no feature is looked up as a product area: memory/areas/<name>.md, else the
# page whose Menu line reads exactly <name>, else the page whose file name that
# Menu gives (" > " → " - ", templates/area.md), printed top first — the plain
# rules before the developer evidence — with the features whose summary.md
# names it. `index` opens with the product areas
# (business-rule count, last change, features), then an overview table (state,
# date, area, tags) newest first, and lists the harvests no close has merged yet. `index_style: obsidian` in the store's config.md adds
# YAML frontmatter and inline #tags to the page; links stay relative markdown.
# No timestamp is written into the page: an unchanged store yields no diff.
#
# Nothing under work/ or archive/ is ever written — an approval-bound artifact
# cannot change because the page was regenerated. `index` writes exactly one
# file, <store>/README.md, and refuses to overwrite one it did not generate.
#
# Exit codes: 0 done / matches found, 1 nothing found (no match, unknown slug,
# no unmerged harvest), 2 usage error or refusal (missing store, unowned path,
# unwritable page).
set -u
# Byte semantics everywhere: under a UTF-8 locale macOS awk compares strings by
# collation, and Hangul menu paths then compare EQUAL to each other — every
# feature would be filed under every product area. Records are matched as bytes.
LC_ALL=C; export LC_ALL

MARKER='<!-- generated by sdlc-kit tools/kb.sh — regenerated by init.sh and close.sh; edits are overwritten -->'
LINE_MAX=200
SUMMARY_MAX=20      # lines of summary.md shown by `show` / `index` (templates/summary.md: twenty at most)
AREA_MAX=40         # lines of an area page shown by `show`
HARVEST_MAX=10      # harvest.md lines shown by `show`
HARVEST_INDEX_MAX=6 # harvest.md lines shown per feature on the contents page
TABLE_GOAL_MAX=120  # bytes of the goal kept in the overview table (≈40 CJK / 120 ASCII characters)
# Field separator for this tool's own record lines. Not a tab: a tab is IFS
# whitespace, so `read` collapses adjacent tabs and an EMPTY field (no tags, no
# date) would shift the fields after it. \037 (ASCII unit separator) is not.
SEP=$(printf '\037')

usage() {
  sed -n '3,12p' "$0" | sed 's/^# \{0,1\}//' >&2
  exit 2
}

# --- store resolution --------------------------------------------------------
kb_is_store() { # <dir> — a directory that holds records
  [ -d "$1/work" ] || [ -d "$1/archive" ] || [ -d "$1/memory" ]
}
kb_label() { # <store dir> → the name results are reported under
  local s="$1" p
  p=$(cd "$s" 2>/dev/null && pwd -P) || { basename "$s"; return; }
  basename "$p"
}
# Prints one store path per line, or fails with a reason on stderr.
kb_stores() { # <store-or-empty> <area-or-empty>
  local store="$1" area="$2" d n=0
  if [ -n "$area" ]; then
    [ -d "$area" ] || { echo "FAIL: no such knowledge folder (--area): $area" >&2; return 2; }
    for d in "$area"/*; do
      [ -d "$d" ] || continue
      [ -L "$d" ] && continue          # never follow a link out of the area
      [ -f "$d/PROJECT" ] || continue  # only stores this kit owns
      printf '%s\n' "$d"; n=$((n + 1))
    done
    [ "$n" -gt 0 ] || { echo "FAIL: no sdlc-kit stores in $area (a store holds a PROJECT record)" >&2; return 2; }
    return 0
  fi
  [ -n "$store" ] || store=".sdlc"
  [ -d "$store" ] || { echo "FAIL: no store at $store — run init.sh first, or pass --store/--area" >&2; return 2; }
  kb_is_store "$store" || { echo "FAIL: $store holds no work/, archive/ or memory/ — not a store" >&2; return 2; }
  printf '%s\n' "$store"
}

# --- record fields -----------------------------------------------------------
KB_DOCS="summary.md origin.md intent.md spec.md plan.md map.md evidence.md delivery.md CLOSED"

kb_field() { # <file> <label> → the first "- <label>: value" line's value (raw); a "> " quote prefix (an Obsidian callout) is dropped first
  [ -f "$1" ] || return 1
  awk -v k="- $2:" '{ sub(/^> ?/, "") } index($0, k) == 1 { sub(/^[^:]*: */, ""); sub(/[ \t\r]*$/, ""); print; exit }' "$1"
}
# A field is read wherever its "- <label>:" line sits in the file — an area
# page's Where line lives inside its <details> evidence block (templates/area.md).
kb_get() { # <file> <label> → the value, or empty when absent or still a template placeholder (<…>, YYYY-…)
  local v; v=$(kb_field "$1" "$2" 2>/dev/null || true)
  case "$v" in ''|'<'*|YYYY*) printf '';; *) printf '%s' "$v";; esac
}
kb_h1() { # <file> [prefix to drop, e.g. "Intent: "] → the first H1, cleaned
  [ -f "$1" ] || return 0
  awk -v p="${2:-}" '/^# /{ sub(/^# */, ""); if (p != "" && index($0, p) == 1) $0 = substr($0, length(p) + 1); sub(/[ \t\r]*$/, ""); print; exit }' "$1"
}
kb_state() { # <dir> → open | the CLOSED state
  if [ -f "$1/CLOSED" ]; then awk '/^state: /{print $2; exit}' "$1/CLOSED"; else echo open; fi
}
kb_closed() { # <dir> <field> → a CLOSED record field (reason, closed_at as YYYY-MM-DD)
  [ -f "$1/CLOSED" ] || return 0
  awk -v k="$2: " 'index($0, k) == 1 { v = substr($0, length(k) + 1); sub(/[ \t\r]*$/, "", v); if (k == "closed_at: ") v = substr(v, 1, 10); print v; exit }' "$1/CLOSED"
}
kb_title() { # <dir> → the Goal line, else the intent's H1 (older intents have no Goal field)
  local g; g=$(kb_get "$1/intent.md" Goal)
  [ -n "$g" ] || g=$(kb_h1 "$1/intent.md" "Intent: ")
  printf '%s' "$g"
}
kb_date() { # <dir> <slug> → YYYY-MM-DD from the intent's Date, else a YYMMDD- slug prefix, else empty
  local d; d=$(kb_get "$1/intent.md" Date)
  case "$d" in [0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]*) printf '%s' "$d" | cut -c1-10; return;; esac
  case "$2" in [0-9][0-9][0-9][0-9][0-9][0-9]-*)
    printf '20%s-%s-%s' "$(printf '%s' "$2" | cut -c1-2)" "$(printf '%s' "$2" | cut -c3-4)" "$(printf '%s' "$2" | cut -c5-6)";; esac
}
kb_tags() { # <dir> → "tag, tag" — summary.md's Tags line (else the intent's), normalized
  local t; t=$(kb_get "$1/summary.md" Tags); [ -n "$t" ] || t=$(kb_get "$1/intent.md" Tags)
  [ -n "$t" ] || return 0
  printf '%s' "$t" | tr -d '[]' | tr ',' '\n' | awk '{ gsub(/^[ \t]+|[ \t]+$/, ""); if ($0 != "") { if (n++) printf ", "; printf "%s", $0 } }'
}
kb_areas() { # <dir> → the product areas summary.md names, one per line
  kb_get "$1/summary.md" Area | tr ',' '\n' | awk '{ gsub(/^[ \t]+|[ \t]+$/, ""); if ($0 != "") print }'
}
kb_join() { awk '{ if (n++) printf ", "; printf "%s", $0 }'; }   # lines on stdin → "a, b"
kb_hashtags() { # "tag, tag" → "#tag #tag" for Obsidian's tag pane (spaces inside a tag become -)
  printf '%s' "$1" | tr ',' '\n' | awk '{ gsub(/^[ \t]+|[ \t]+$/, ""); gsub(/[ \t]+/, "-"); if ($0 != "") { if (n++) printf " "; printf "#%s", $0 } }'
}
# The readable body of a record: template comments (single- and multi-line),
# blank lines and unfilled `<placeholder>` lines are dropped; the H1 is dropped;
# `## X` (and deeper headings), a `<summary>X</summary>` line and a
# `> [!type]- X` callout line (the area page's evidence block, HTML or
# Obsidian form) become `X:` labels — the callout's own lines print without
# their "> " prefix — so a record embedded in the
# contents page cannot hijack its outline. A heading with nothing under it yet
# is dropped too: an unfinished record prints only what is known. A markdown
# table prints as written, except a template placeholder row (every cell after
# the first is only `<…>`); a table left with no data row loses its header too.
kb_body() { # <file>
  [ -f "$1" ] || return 0
  awk '
    function ph(l,   a, n, i, x) { # a template placeholder row: every cell after the first is <…>
      gsub(/\\\|/, "\001", l); sub(/^[ \t]*\|/, "", l); sub(/\|[ \t]*$/, "", l)
      n = split(l, a, "|")
      for (i = 2; i <= n; i++) { x = a[i]; gsub(/^[ \t]+|[ \t]+$/, "", x); if (x !~ /^<.*>$/) return 0 }
      return n >= 2
    }
    BEGIN { c = 0; q = 0; tb = 0 }
    {
      line = $0
      if (c) { i = index(line, "-->"); if (i) { c = 0; line = substr(line, i + 3) } else next }
      while ((s = index(line, "<!--")) > 0) {
        rest = substr(line, s); e = index(rest, "-->")
        if (e) line = substr(line, 1, s - 1) substr(rest, e + 3)
        else { line = substr(line, 1, s - 1); c = 1; break }
      }
      sub(/[ \t\r]+$/, "", line)
      if (q) { if (line ~ /^>/) sub(/^> ?/, "", line); else q = 0 }
      if (line ~ /^> *\[![A-Za-z-]+\][-+]?/) { sub(/^> *\[![A-Za-z-]+\][-+]? */, "", line); pend = line ":"; q = 1; next }
      if (line ~ /^# /) next
      if (line ~ /^##+ /) { sub(/^#+ +/, "", line); pend = line ":"; next }
      if (line ~ /^[ \t]*<summary>.*<\/summary>[ \t]*$/) { sub(/^[ \t]*<summary>[ \t]*/, "", line); sub(/[ \t]*<\/summary>[ \t]*$/, "", line); pend = line ":"; next }
      if (line ~ /^[ \t]*\|/) {   # a table: hold the header and separator until a data row shows
        if (!tb) { tb = 1; hd = line; hs = ""; next }
        if (hd != "" && hs == "" && line ~ /^[ \t]*\|[ \t:|-]+$/) { hs = line; next }
        if (ph(line)) next
        if (pend != "") { print pend; pend = "" }
        if (hd != "") { print hd; if (hs != "") print hs; hd = ""; hs = "" }
        print line; next
      }
      tb = 0; hd = ""; hs = ""
      if (line ~ /^[ \t]*$/) next
      if (line ~ /^[ \t]*[-*] *<[^>]*>[ \t]*$/) next
      if (line ~ /^[ \t]*<[^>]*>[ \t]*$/) next
      if (line ~ /^[ \t]*[-*] *[A-Za-z0-9-]+: *<[^>]*>[ \t]*$/) next
      if (pend != "") { print pend; pend = "" }
      print line
    }' "$1"
}
kb_summary() { kb_body "$1/summary.md" | awk '!/^[ \t]*[-*] *(Tags|Area):/'; }   # <dir>; Tags and Area are shown on the meta line
kb_print_bounded() { # <max> <indent> <"more" location>; text on stdin
  awk -v m="$1" -v ind="$2" -v where="$3" '
    { n++; if (n <= m) print ind $0 }
    END { if (n > m) printf "%s… %d more line(s): %s\n", ind, n - m, where }'
}
kb_count_lines() { awk '!/:$/ { n++ } END { print n + 0 }'; }   # kb_body text on stdin → content lines (labels excluded)

# --- features ----------------------------------------------------------------
# "<kind> <slug> <dir>" lines. Feature directories that are symlinks are never
# read (the gates refuse them too).
kb_features() { # <store>
  local store="$1" kind d
  for kind in work archive; do
    [ -d "$store/$kind" ] || continue
    for d in "$store/$kind"/*; do
      [ -d "$d" ] || continue
      if [ -L "$d" ]; then echo "note: skipped $d — a feature directory that is a symlink is not read" >&2; continue; fi
      printf '%s %s %s\n' "$kind" "$(basename "$d")" "$d"
    done
  done
}
# "<sortkey>\t<kind>\t<slug>\t<dir>" lines of one kind, newest first: closed
# features by closed_at, open ones by the intent's date (undated ones last).
kb_features_sorted() { # <store> <kind>
  local kind slug dir key
  kb_features "$1" 2>/dev/null | while read -r kind slug dir; do
    [ "$kind" = "$2" ] || continue
    key=$(kb_closed "$dir" closed_at); [ -n "$key" ] || key=$(kb_date "$dir" "$slug"); [ -n "$key" ] || key="0000-00-00"
    printf '%s\037%s\037%s\037%s\n' "$key" "$kind" "$slug" "$dir"
  done | LC_ALL=C sort -t "$SEP" -k1,1r -k3,3
}
# "<state>\t<date>\t<tags>\t<areas>\t<title>" — the fields both index passes print.
kb_meta() { # <dir> <slug> <style>
  local tags; tags=$(kb_tags "$1")
  [ "$3" = obsidian ] && [ -n "$tags" ] && tags=$(kb_hashtags "$tags")
  printf '%s\037%s\037%s\037%s\037%s\n' "$(kb_state "$1")" "$(kb_date "$1" "$2")" "$tags" \
    "$(kb_areas "$1" | kb_join)" "$(kb_title "$1" | tr '\t' ' ')"
}

# --- product areas (memory/areas/*.md, templates/area.md) --------------------
kb_area_pages() { # <store> → page paths; a page that is a symlink is not read
  local f
  [ -d "$1/memory/areas" ] || return 0
  for f in "$1/memory/areas"/*.md; do [ -f "$f" ] && [ ! -L "$f" ] && printf '%s\n' "$f"; done
}
kb_area_menu() { # <page> → its Menu line, else its H1, else its file name (an unfilled page)
  local m; m=$(kb_get "$1" Menu); [ -n "$m" ] || m=$(kb_h1 "$1" "Area: ")
  case "$m" in ''|'<'*) m=$(basename "$1" .md);; esac
  printf '%s' "$m"
}
# Live rules: the "| P<n> | rule |" table rows, and the "- P<n>: rule" list
# lines pages written before the table form still hold — counted only ABOVE
# the evidence block (the `<details>` or `> [!…]` line), whose rows carry the
# same P-numbers. Row shapes only, never header words. A retired rule reads
# "| ~~P…" or "- ~~P…", and an unfilled template row "| P1 | <…> |" (or line
# "- P1: <…>") — none of them counts.
kb_area_rules() {
  awk '/^[ \t]*<details/ || /^> *\[!/ { exit }
    /^- P[0-9]+:/ && !/^- P[0-9]+: *</ { n++; next }
    /^\| *P[0-9]+ *\|/ { r = $0; sub(/^\| *P[0-9]+ *\| */, "", r); if (r !~ /^</) n++ }
    END { print n + 0 }' "$1"
}
kb_area_last() { # <page> → the date of History's first (newest) row "| YYYY-MM-DD |", or list line "- YYYY-MM-DD"
  awk '/^[ \t]*<details/ || /^> *\[!/ { exit }
    /^## /{ h = ($0 ~ /^## History/); next }
    h && (/^- [0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]/ || /^\| *[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9] *\|/) {
      match($0, /[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]/); print substr($0, RSTART, 10); exit }' "$1"
}
# "<area><SEP><kind><SEP><slug><SEP><dir>" for every feature naming an area.
kb_area_refs() { # <store>
  local kind slug dir a
  kb_features "$1" 2>/dev/null | while read -r kind slug dir; do
    kb_areas "$dir" | while IFS= read -r a; do printf '%s\037%s\037%s\037%s\n' "$a" "$kind" "$slug" "$dir"; done
  done
}
kb_area_of() { # <menu> <file name>; kb_area_refs lines on stdin → the lines naming that page
  awk -F "$SEP" -v a="$1" -v b="$2" '$1 == a || $1 == b'
}
kb_area_slugs() { awk -F "$SEP" '{ if (n++) printf ", "; printf "%s", $3 }'; }   # kb_area_refs lines → "slug, slug"
# The file name a Menu gives its page (templates/area.md): each " > " written
# " - ", and every character a Windows or macOS file name may not hold
# (/ \ : * ? " < > |) replaced with "-". Byte-wise under LC_ALL=C: no byte of a
# multibyte (Hangul) character falls in an ASCII class, so it passes unchanged.
kb_area_file() { printf '%s' "$1" | sed -e 's/ > / - /g' -e 's#[/\\:*?"<>|]#-#g'; }
kb_area_page() { # <store> <file name, no .md> → the page when it exists; a name with / or \ or a leading . is refused
  case "$2" in ''|*/*|*\\*|.*) return 1;; esac
  [ -f "$1/memory/areas/$2.md" ] && [ ! -L "$1/memory/areas/$2.md" ] && printf '%s\n' "$1/memory/areas/$2.md"
}
kb_area_find() { # <store> <name> → the page: <name>.md, else the page whose Menu is <name>, else the page named by that Menu
  local f d
  kb_area_page "$1" "$2" && return 0
  f=$(kb_area_pages "$1" | while IFS= read -r f; do
    [ "$(kb_area_menu "$f")" = "$2" ] && { printf '%s\n' "$f"; break; }
  done)
  [ -n "$f" ] && { printf '%s\n' "$f"; return 0; }
  d=$(kb_area_file "$2")
  [ "$d" = "$2" ] || kb_area_page "$1" "$d"
  return 0
}
# A page's link target on the contents page. File names hold spaces (and, from a
# Menu, Hangul): space % ( ) [ ] # < > are percent-encoded so the link works in
# GitHub and Obsidian alike; other UTF-8 bytes stay as they are, the form
# Obsidian writes its own markdown links in.
kb_area_href() { # <file name> → memory/areas/<encoded>
  printf 'memory/areas/%s' "$(printf '%s' "$1" | sed -e 's/%/%25/g' -e 's/ /%20/g' -e 's/(/%28/g' -e 's/)/%29/g' \
    -e 's/\[/%5B/g' -e 's/\]/%5D/g' -e 's/#/%23/g' -e 's/</%3C/g' -e 's/>/%3E/g')"
}
# "<slug>\t<lines>\t<dir>" for every open feature whose harvest.md still holds
# candidates — the one definition `index` and `harvest` share.
kb_unmerged() { # <store>
  local kind slug dir n
  kb_features "$1" 2>/dev/null | while read -r kind slug dir; do
    [ "$kind" = work ] && [ -f "$dir/harvest.md" ] || continue
    n=$(kb_body "$dir/harvest.md" | kb_count_lines)
    [ "$n" -gt 0 ] && printf '%s\037%s\037%s\n' "$slug" "$n" "$dir"
  done
}
kb_lessons() { # <store> <slug> → lesson paths naming the slug
  local f
  [ -d "$1/memory/lessons" ] || return 0
  for f in "$1/memory/lessons"/*"$2"*; do [ -f "$f" ] && printf '%s\n' "$f"; done
}
# Idle time for the harvest report: whole days since the newest of the feature's
# own records (never scratch/). GNU stat first: on GNU `-f %m` is not a failure
# but the MOUNT POINT of the file system ("/"), so a BSD-first order silently
# returns text on Linux and Git Bash; `-c` is an illegal option on BSD/macOS,
# so this order fails over cleanly there.
kb_idle_days() { # <feature dir> → days, or empty when unknown
  local f m newest=""
  for f in "$1"/*.md "$1"/CLOSED; do
    [ -f "$f" ] || continue
    m=$(stat -c %Y "$f" 2>/dev/null || stat -f %m "$f" 2>/dev/null || true)
    case "$m" in ''|*[!0-9]*) continue;; esac
    if [ -z "$newest" ] || [ "$m" -gt "$newest" ]; then newest="$m"; fi
  done
  [ -n "$newest" ] && echo $(( ( $(date +%s) - newest ) / 86400 ))
}

# --- index -------------------------------------------------------------------
kb_index_style() { # <store> → obsidian | plain, from the store's config.md
  if [ -f "$1/config.md" ] && awk '/^index_style:[ \t]*obsidian/{ f = 1 } END { exit !f }' "$1/config.md"; then echo obsidian; else echo plain; fi
}
kb_table_cell() { # text → one table cell: pipes escaped, newlines gone, bounded
  # Bounded in BYTES under LC_ALL=C (awk's length/substr are not UTF-8 aware
  # everywhere); the cut backs off to a character boundary so a multibyte
  # character is never split into a broken glyph.
  printf '%s' "$1" | tr '\n\r' '  ' | sed 's/|/\\|/g' | LC_ALL=C awk -v m="$TABLE_GOAL_MAX" '{
    if (length($0) <= m) { print; next }
    i = m + 1
    while (i > 1 && substr($0, i, 1) >= "\200" && substr($0, i, 1) < "\300") i--
    print substr($0, 1, i - 1) "…" }'
}
kb_index() { # <store>
  local store="$1" style page label kind slug dir doc f key state date tags areas title when body n refs pages menu f_last
  page="$store/README.md"; label=$(kb_label "$store"); style=$(kb_index_style "$store")
  if [ -e "$page" ]; then
    if [ -L "$page" ]; then echo "FAIL: $page is a symlink — refusing to write through it" >&2; return 2; fi
    if ! head -n 12 "$page" 2>/dev/null | grep -qF "$MARKER"; then
      echo "FAIL: $page was not generated by kb.sh — refusing to overwrite a page you wrote." >&2
      echo "  Rename it (or delete it) if you want the generated contents page here." >&2
      return 2
    fi
  fi
  {
    # frontmatter first (Obsidian reads it only at line 1); no generated-at
    # stamp — a page whose content did not change must not produce a diff
    [ "$style" = obsidian ] && printf -- '---\ntitle: "Knowledge: %s"\nsdlc_store: "%s"\ntags: [sdlc-kit, knowledge]\n---\n' "$label" "$label"
    printf '%s\n' "$MARKER"
    printf '\n# Knowledge: %s\n\n' "$label"
    if [ -f "$store/PROJECT" ]; then
      printf 'Records of `%s` (checkout `%s`).\n\n' \
        "$(awk '/^project: /{sub(/^project: /,""); sub(/[ \t\r]*$/,""); print; exit}' "$store/PROJECT")" \
        "$(awk '/^checkout_id: /{print $2; exit}' "$store/PROJECT")"
    fi
    printf 'Search: `tools/kb.sh search "<text>"` · one feature or product area: `tools/kb.sh show <slug | area>` · knowledge not merged yet: `tools/kb.sh harvest`\n'

    # --- product areas: what a reader navigates by -----------------------------
    # One row per area page, then any area a feature names that has no page yet
    # (its rules reach memory/ at the close merge — AGENTS.md rule 4).
    refs=$(kb_area_refs "$store")
    pages=$(kb_area_pages "$store")
    if [ -n "$pages$refs" ]; then
      printf '\n## Product areas\n\n| Area | Rules | Last change | Features |\n|---|---|---|---|\n'
      printf '%s\n' "$pages" | while IFS= read -r f; do
        [ -n "$f" ] || continue
        menu=$(kb_area_menu "$f")
        body=$(printf '%s\n' "$refs" | kb_area_of "$menu" "$(basename "$f" .md)" | kb_area_slugs)
        f_last=$(kb_area_last "$f")
        printf '| [%s](%s) | %s | %s | %s |\n' "$(kb_table_cell "$menu")" "$(kb_area_href "$(basename "$f")")" \
          "$(kb_area_rules "$f")" "${f_last:-—}" "${body:-—}"
      done
      printf '%s\n' "$refs" | awk -F "$SEP" 'NF && !seen[$1]++ { print $1 }' | while IFS= read -r menu; do
        [ -n "$(kb_area_find "$store" "$menu")" ] && continue
        printf '| %s — no page yet | — | — | %s |\n' "$(kb_table_cell "$menu")" "$(printf '%s\n' "$refs" | kb_area_of "$menu" "" | kb_area_slugs)"
      done
    fi

    # --- overview: one row per feature, open first, newest first --------------
    printf '\n## Overview\n\n| Feature | State | Date | Area | Tags | Goal |\n|---|---|---|---|---|---|\n'
    for kind in work archive; do
      kb_features_sorted "$store" "$kind" | while IFS="$SEP" read -r key kind slug dir; do
        [ -n "${slug:-}" ] || continue
        IFS="$SEP" read -r state date tags areas title <<EOF
$(kb_meta "$dir" "$slug" "$style")
EOF
        [ "$key" = "0000-00-00" ] && key="—"   # the column shows what the row is sorted by: closed_at once closed, else the intent's date
        if [ -f "$dir/intent.md" ]; then printf '| [%s](%s/%s/intent.md) ' "$slug" "$kind" "$slug"; else printf '| %s ' "$slug"; fi
        printf '| %s | %s | %s | %s | %s |\n' "$state" "$key" "$(kb_table_cell "${areas:-—}")" "${tags:-—}" "$(kb_table_cell "$title")"
      done
    done
    [ -n "$(kb_features "$store" 2>/dev/null)" ] || printf '| _none_ | | | | | |\n'

    # --- knowledge that exists but is not in memory/ yet ----------------------
    # AGENTS.md rule 4: harvest.md is merged at close. A loop that never closes
    # leaves it invisible to every stage start; this section makes it visible
    # from the entry page. Read-only — merging stays a deliberate step.
    body=$(kb_unmerged "$store")
    if [ -n "$body" ]; then
      printf '\n## Knowledge not merged yet\n\n'
      printf '%s\n' "$body" | awk -F "$SEP" '{ n++; c += $2 } END { printf "%d open feature(s) hold %d line(s) in harvest.md that no close has merged into memory/ (AGENTS.md rule 4). `tools/kb.sh harvest` lists them with their idle time.\n", n, c }'
      printf '%s\n' "$body" | while IFS="$SEP" read -r slug n dir; do
        printf '\n### %s — %s line(s) · [harvest.md](work/%s/harvest.md)\n\n' "$slug" "$n" "$slug"
        kb_body "$dir/harvest.md" | kb_print_bounded "$HARVEST_INDEX_MAX" "" "work/$slug/harvest.md"
      done
    fi

    # --- one section per feature ----------------------------------------------
    for kind in work archive; do
      [ -d "$store/$kind" ] || continue
      case "$kind" in work) printf '\n## Open features\n';; archive) printf '\n## Closed features\n';; esac
      kb_features_sorted "$store" "$kind" | while IFS="$SEP" read -r key kind slug dir; do
        [ -n "${slug:-}" ] || continue
        IFS="$SEP" read -r state date tags areas title <<EOF
$(kb_meta "$dir" "$slug" "$style")
EOF
        when="${date:+ · $date}"; f=$(kb_closed "$dir" closed_at); [ -n "$f" ] && when="$when · closed $f"
        printf '\n### %s — %s%s%s%s\n' "$slug" "$state" "$when" "${areas:+ · $areas}" "${tags:+ · $tags}"
        [ -n "$title" ] && printf '\n%s\n' "$title"
        body=$(kb_summary "$dir")
        [ -n "$body" ] && { printf '\n'; printf '%s\n' "$body" | kb_print_bounded "$SUMMARY_MAX" "" "$kind/$slug/summary.md"; }
        f=$(kb_get "$dir/intent.md" Track); [ -n "$f" ] && printf '\nTrack: %s\n' "$f"
        f=$(kb_closed "$dir" reason); [ -n "$f" ] && printf '\nClosed: %s\n' "$f"
        printf '\n'
        for doc in $KB_DOCS; do [ -f "$dir/$doc" ] && printf -- '- [%s](%s/%s/%s)\n' "$doc" "$kind" "$slug" "$doc"; done
        [ -f "$dir/harvest.md" ] && printf -- '- [harvest.md](%s/%s/harvest.md) — not merged into memory/ yet\n' "$kind" "$slug"
        kb_lessons "$store" "$slug" | while read -r f; do
          printf -- '- [lesson: %s](memory/lessons/%s)\n' "$(kb_h1 "$f" "Lesson: ")" "$(basename "$f")"
        done
      done
      [ -n "$(kb_features "$store" 2>/dev/null | awk -v k="$kind" '$1 == k')" ] || printf '\n_none_\n'
    done
    printf '\n## Memory\n\n'
    for f in POLICY.md INDEX.md DOMAIN.md; do [ -f "$store/memory/$f" ] && printf -- '- [%s](memory/%s)\n' "$f" "$f"; done
    [ -d "$store/memory/areas" ] && printf -- '- [areas/](memory/areas/)\n'
    [ -d "$store/memory/lessons" ] && printf -- '- [lessons/](memory/lessons/)\n'
    [ -f "$store/config.md" ] && printf -- '- [config.md](config.md)\n'
    printf ''
  } > "$page.kb-tmp.$$" 2>/dev/null || { rm -f "$page.kb-tmp.$$"; echo "FAIL: cannot write $page" >&2; return 2; }
  mv "$page.kb-tmp.$$" "$page" || { rm -f "$page.kb-tmp.$$"; echo "FAIL: cannot write $page" >&2; return 2; }
  echo "contents page: $page ($style)"
}

# --- list --------------------------------------------------------------------
kb_list() { # <store>
  local n=0 kind slug dir
  printf '%s\n' "$(kb_label "$1")"
  while read -r kind slug dir; do
    [ -n "${slug:-}" ] || continue
    printf '  %-9s %-28s %s\n' "$kind" "$slug" "$(kb_state "$dir")"; n=$((n + 1))
  done <<EOF
$(kb_features "$1" 2>/dev/null)
EOF
  [ "$n" -gt 0 ] || printf '  (no features)\n'
}

# --- show --------------------------------------------------------------------
# A digest, not a table of contents: what the feature is for, where it stands,
# what it learned — then the paths. Every line comes from a record; nothing is
# summarized by this tool, only selected and bounded.
kb_show() { # <store> <slug> → 0 when found
  local store="$1" slug="$2" kind dir doc found=1 v f meta body
  for kind in work archive; do
    dir="$store/$kind/$slug"
    [ -d "$dir" ] || continue
    [ -L "$dir" ] && { echo "note: $dir is a symlink — not read" >&2; continue; }
    found=0
    printf '%s/%s/%s — %s\n' "$(kb_label "$store")" "$kind" "$slug" "$(kb_state "$dir")"
    v=$(kb_title "$dir"); [ -n "$v" ] && printf '  %s\n' "$v"
    meta=""
    for v in Track Type Date "Requested by" Refs; do f=$(kb_get "$dir/intent.md" "$v"); [ -n "$f" ] && meta="$meta · $v: $f"; done
    f=$(kb_areas "$dir" | kb_join); [ -n "$f" ] && meta="$meta · Area: $f"
    f=$(kb_tags "$dir"); [ -n "$f" ] && meta="$meta · Tags: $f"
    [ -n "$meta" ] && printf '  %s\n' "${meta# · }"
    body=$(kb_summary "$dir")
    [ -n "$body" ] && { printf '  Summary:\n'; printf '%s\n' "$body" | kb_print_bounded "$SUMMARY_MAX" "    " "$kind/$slug/summary.md"; }
    v=$(kb_get "$dir/delivery.md" Target)
    if [ -n "$v" ]; then
      printf '  Delivered: %s' "$v"
      f=$(kb_get "$dir/delivery.md" Confirmed); [ -n "$f" ] && printf ' (confirmed: %s)' "$f"
      f=$(kb_get "$dir/delivery.md" Handoff); [ -n "$f" ] && printf ' · handoff: %s' "$f"
      printf '\n'
    fi
    v=$(kb_closed "$dir" reason)
    [ -n "$v" ] && { printf '  Closed: %s' "$v"; f=$(kb_closed "$dir" closed_at); [ -n "$f" ] && printf ' (%s)' "$f"; printf '\n'; }
    body=$(kb_body "$dir/harvest.md")
    [ -n "$body" ] && { printf '  Not merged into memory/ yet (harvest.md):\n'; printf '%s\n' "$body" | kb_print_bounded "$HARVEST_MAX" "    " "$kind/$slug/harvest.md"; }
    v=$(kb_lessons "$store" "$slug")
    if [ -n "$v" ]; then
      printf '  Lessons:\n'
      printf '%s\n' "$v" | while read -r f; do printf '    %s — memory/lessons/%s\n' "$(kb_h1 "$f" "Lesson: ")" "$(basename "$f")"; done
    fi
    printf '  Documents:\n'
    for doc in $KB_DOCS harvest.md; do [ -f "$dir/$doc" ] && printf '    %s/%s/%s\n' "$kind" "$slug" "$doc"; done
  done
  return $found
}

# One product area: its page, bounded, then every feature that names it. An
# area features name that has no page yet is shown with those features.
kb_show_area() { # <store> <name> → 0 when found
  local store="$1" page menu refs drive
  page=$(kb_area_find "$store" "$2")
  if [ -n "$page" ]; then
    menu=$(kb_area_menu "$page")
    printf '%s/memory/areas/%s — product area\n  %s\n' "$(kb_label "$store")" "$(basename "$page")" "$menu"
    # the Drive line sits in the evidence block at the bottom, which a long page's bound cuts: print it first
    drive=$(kb_get "$page" Drive)
    [ -z "$drive" ] || printf '  Drive: %s\n' "$drive"
    kb_body "$page" | awk '!/^[ \t]*[-*] *(Menu|Drive):/' | kb_print_bounded "$AREA_MAX" "  " "memory/areas/$(basename "$page")"
    refs=$(kb_area_refs "$store" | kb_area_of "$menu" "$(basename "$page" .md)")
  else
    refs=$(kb_area_refs "$store" | kb_area_of "$2" "")
    [ -n "$refs" ] || return 1
    printf '%s — product area, no page yet (its rules reach memory/areas/ when a feature naming it closes shipped)\n' "$2"
  fi
  [ -n "$refs" ] || return 0
  printf '  Features naming this area:\n'
  printf '%s\n' "$refs" | while IFS="$SEP" read -r _ kind slug dir; do
    printf '    %s/%s — %s — %s\n' "$kind" "$slug" "$(kb_state "$dir")" "$(kb_title "$dir")"
  done
  return 0
}

# --- harvest -----------------------------------------------------------------
# Which open features hold knowledge that is not in memory/ yet, and for how
# long nobody has touched them — the trigger the close-only merge lacked. A
# feature idle past --stale may be merged WITHOUT closing (same procedure, one
# at a time, in the owning checkout — AGENTS.md rule 4). Reports only.
kb_harvest() { # <store> <stale-days> → prints; echoes "<found> <stale>" on fd 3
  local slug n dir idle flag found=0 nstale=0
  printf '%s\n' "$(kb_label "$1")"
  while IFS="$SEP" read -r slug n dir; do
    [ -n "${slug:-}" ] || continue
    found=$((found + 1)); idle=$(kb_idle_days "$dir")
    if [ -z "$idle" ]; then flag="idle: unknown"
    elif [ "$idle" -ge "$2" ]; then flag="STALE — idle ${idle}d (≥ $2d): merge without closing"; nstale=$((nstale + 1))
    else flag="active — idle ${idle}d"; fi
    printf '  %-32s %3s line(s)   %s\n' "$slug" "$n" "$flag"
  done <<EOF
$(kb_unmerged "$1")
EOF
  [ "$found" -gt 0 ] || printf '  (no unmerged harvest)\n'
  echo "$found $nstale" >&3
}

# --- search ------------------------------------------------------------------
# Literal only (grep -F): a query is text a human remembers, not a regex, and a
# stray `.` or `*` must not silently widen the search. `-e` keeps a query that
# starts with `-` a query.
kb_searchable() { # <store> → readable record paths, one per line
  local d
  for d in work archive memory; do
    [ -d "$1/$d" ] || continue
    find "$1/$d" -type f \( -name '*.md' -o -name 'CLOSED' \) 2>/dev/null
  done | awk '
    $0 ~ /\/scratch\// { next }
    $0 ~ /\/approvals\// { next }
    { n = split($0, p, "/"); b = p[n] }
    b == "progress.md" || b == "baseline.txt" || b == "checkpoint.md" || b == "verify-receipt.md" || b == "verify-baseline.md" { next }
    { print }
  ' | LC_ALL=C sort
}
kb_search() { # <store> <query> <limit> <shown-so-far> → prints, echoes the new count on fd 3
  local store="$1" q="$2" limit="$3" shown="$4" label f rel hits h
  label=$(kb_label "$store")
  while IFS= read -r f; do
    [ -n "$f" ] || continue
    hits=$(grep -F -n -e "$q" -- "$f" 2>/dev/null) || continue
    rel=${f#"$store"/}
    while IFS= read -r h; do
      [ -n "$h" ] || continue
      if [ "$shown" -ge "$limit" ]; then shown=$((shown + 1)); continue; fi
      printf '%s/%s:%s\n' "$label" "$rel" "$(printf '%s' "$h" | cut -c1-$LINE_MAX)"
      shown=$((shown + 1))
    done <<EOF
$hits
EOF
  done <<EOF
$(kb_searchable "$store")
EOF
  echo "$shown" >&3
}

# --- argument parsing --------------------------------------------------------
[ $# -ge 1 ] || usage
cmd="$1"; shift
# One positional argument at most (a slug, or the literal to search for). Flags
# may follow it. A query that starts with `-` goes after `--`; an unknown option
# is an error, never a silently ignored word.
store=""; area=""; limit=50; stale=30; arg=""; have_arg=0; endopts=0
while [ $# -gt 0 ]; do
  if [ "$endopts" -eq 0 ]; then
    case "$1" in
      --) endopts=1; shift; continue;;
      --store) [ $# -ge 2 ] || usage; store="$2"; shift 2; continue;;
      --store=*) store="${1#--store=}"; shift; continue;;
      --area) [ $# -ge 2 ] || usage; area="$2"; shift 2; continue;;
      --area=*) area="${1#--area=}"; shift; continue;;
      --limit) [ $# -ge 2 ] || usage; limit="$2"; shift 2; continue;;
      --limit=*) limit="${1#--limit=}"; shift; continue;;
      --stale) [ $# -ge 2 ] || usage; stale="$2"; shift 2; continue;;
      --stale=*) stale="${1#--stale=}"; shift; continue;;
      -h|--help) usage;;
      -?*) echo "FAIL: unknown option '$1' (a query starting with '-' goes after --)" >&2; exit 2;;
    esac
  fi
  [ "$have_arg" -eq 0 ] || { echo "FAIL: one argument at most; quote a query that contains spaces" >&2; exit 2; }
  arg="$1"; have_arg=1; shift
done
if [ "$have_arg" -eq 1 ]; then set -- "$arg"; else set --; fi
case "$limit" in (''|*[!0-9]*) echo "FAIL: --limit takes a number" >&2; exit 2;; esac
[ "$limit" -gt 0 ] || { echo "FAIL: --limit must be > 0" >&2; exit 2; }
case "$stale" in (''|*[!0-9]*) echo "FAIL: --stale takes a number of days" >&2; exit 2;; esac

stores=$(kb_stores "$store" "$area") || exit 2

rc=0
case "$cmd" in
  index)
    [ -z "$area" ] || { echo "FAIL: index writes one store's page — use --store" >&2; exit 2; }
    # `index` is the one WRITE this tool performs. Against the default store —
    # this project's ./.sdlc, which may be a link into an external area — it runs
    # the same ownership check the gates run, so a copied checkout cannot write
    # into the original's store (gates/_common.sh sdlc_store_owner_ok). An
    # explicit --store is a deliberate choice of a store and is not second-guessed;
    # reading (list, show, search, harvest) is never bound to a checkout at all.
    if [ -z "$store" ]; then
      kb_kit=$(cd "$(dirname "$0")/.." 2>/dev/null && pwd) || kb_kit=""
      [ -n "$kb_kit" ] && [ -f "$kb_kit/gates/_common.sh" ] || {
        echo "FAIL: gates/_common.sh is not next to $0 — the ownership check cannot run" >&2; exit 2; }
      . "$kb_kit/gates/_common.sh"
      sdlc_store_owner_ok || exit 2
    fi
    kb_index "$stores" || exit $?;;
  list)
    while IFS= read -r s; do [ -n "$s" ] && kb_list "$s"; done <<EOF
$stores
EOF
    ;;
  show)
    [ $# -ge 1 ] || { echo "FAIL: show needs a feature slug or a product area" >&2; exit 2; }
    slug="$1"; rc=1
    while IFS= read -r s; do
      [ -n "$s" ] || continue
      if kb_show "$s" "$slug"; then rc=0; fi
    done <<EOF
$stores
EOF
    if [ "$rc" -ne 0 ]; then
      while IFS= read -r s; do
        [ -n "$s" ] || continue
        if kb_show_area "$s" "$slug"; then rc=0; fi
      done <<EOF
$stores
EOF
    fi
    [ "$rc" -eq 0 ] || echo "no feature or product area '$slug' in the store(s) searched" >&2;;
  harvest)
    [ $# -eq 0 ] || { echo "FAIL: harvest takes no argument (use --stale <days>)" >&2; exit 2; }
    total=0; tstale=0
    while IFS= read -r s; do
      [ -n "$s" ] || continue
      counts=$(kb_harvest "$s" "$stale" 3>&1 >&4)
      total=$((total + ${counts% *})); tstale=$((tstale + ${counts#* }))
    done 4>&1 <<EOF
$stores
EOF
    if [ "$total" -eq 0 ]; then
      echo "no unmerged harvest — every candidate is in memory/ (or no feature wrote one)" >&2; rc=1
    else
      echo "$total unmerged harvest(s), $tstale idle ≥ ${stale} day(s)."
      echo "Merge (AGENTS.md rule 4): read work/<slug>/harvest.md → area pages (rules, history) + DOMAIN.md facts + lesson files and INDEX.md lines, then delete harvest.md."
      echo "A STALE feature may be merged without closing; it stays open. One merge at a time, in the owning checkout."
    fi;;
  search)
    [ $# -ge 1 ] || { echo "FAIL: search needs the text to look for" >&2; exit 2; }
    q="$1"
    [ -n "$q" ] || { echo "FAIL: empty search text" >&2; exit 2; }
    shown=0
    while IFS= read -r s; do
      [ -n "$s" ] || continue
      shown=$(kb_search "$s" "$q" "$limit" "$shown" 3>&1 >&4)
    done 4>&1 <<EOF
$stores
EOF
    if [ "$shown" -eq 0 ]; then
      echo "no match for '$q'" >&2; rc=1
    elif [ "$shown" -gt "$limit" ]; then
      echo "… $((shown - limit)) more match(es) not shown (--limit $limit)" >&2
    fi;;
  *) echo "FAIL: unknown command '$cmd'" >&2; usage;;
esac
exit $rc
